### ISSUE TITLE
Comando incorrecto

### ISSUE THREAD

**Issue by LanderU** [erlerobot/ros-hydro-erle-statusled#1]
En el README.md falta una **"d"**:

<code> 
catkin_make_isolate --install -DCMAKE_BUILD_TYPE=Release --pkg ros_erle_statusled
 </code>

Y es:

<code>
catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --pkg ros_erle_statusled </code>

**Comment by vmayoral** [comment]
Gracias por el catch @LanderU, querrías hacer un Pull Request?

**Comment by ahcorde** [comment]
Solucionado en este [commit](https://github.com/erlerobot/ros_erle_statusled/commit/2c4b76060d02eb8ba5f7d4e825f4149a25471fae)

**Comment by ahcorde** [comment]
La próxima animate y haz el cambio tu ;)
